######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 24 17:11:20 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
