.PHONY: all
all:
	@echo 1111 MAKE = $(MAKE)
	$(MAKE) -C libmath
	$(MAKE) -C libprint
	$(MAKE) -C calc

.PHONY: clean
clean:
	$(MAKE) -C libmath clean
	$(MAKE) -C libprint clean
	$(MAKE) -C calc clean

